### PR TITLE
Enforce DNA alphabet for feature sequences

### LINKED ISSUE #30: Doc for sequence mentions DNA alphabet but is never enforced
Documentation for sequence attribute mentions DNA alphabet
https://github.com/nmdp-bioinformatics/service-feature/blob/master/resource/src/main/java/org/nmdp/service/feature/resource/FeatureRequest.java#L72

but is never enforced.

Consider:
- remove doc and allow any characters
- enforce DNA alphabet with no ambiguity
- enforce DNA alphabet (including IUPAC ambiguity) using biojava
- provide alphabet request attribute `{DNA, RNA, AA/PROTEIN}` and enforce using biojava

### PR DESCRIPTION
**Pull request by heuermh**
Fixes #30

### CODE REVIEW

**Comment by fscheel** [comment]
Shouldn't the regex be `^[ACTG]*$`? Also not sure whether the sequence may be the empty string...

**Comment by heuermh** [comment]
@fscheel Yep, you're right.  My regex skills are rusty.  Will fix and rebase.

**Comment by fscheel** [comment]
:+1:
Since we'll disallow empty strings in another PR

**Comment by heuermh** [comment]
Thanks!

**Pull request merged**
