### PR TITLE
return HTTP error codes on user input errors

### LINKED ISSUE #38: Return useful error codes
When doing faulty requests to the webserver, they are logged on the server and the server returns 500 error codes. It's impossibly for the client to identify whether the call was faulty or the server has issues and it should try again later.

### PR DESCRIPTION
**Pull request by fscheel**
Not null and basic value checks are now done in the feature resource, the common
API definition. Those unchecked exceptions are caught and wrapped into a custom
checked exception (`UserInputException`). This in turn is mapped to a `400`
response by the service.

This fixes nmdp-bioinformatics/service-feature#38

### CODE REVIEW

**Comment by heuermh** [comment]
@epearson-nmdp I believe these new `check` statements are in the wrong place.  The API in `FeatureService` is what asserts the preconditions, not `FeatureResource`.  What would you think about removing most of the `check` statements in this pull request and instead adding the try catch block around the service call?

**Comment by fscheel** [comment]
Looking back at it, this might be a better solution. However, I am not sure if you are able to discriminate between the exceptions that are thrown when a user input is wrong and other exceptions, which should probably still throw error 500.

Another option is to move the `UserInputException` into the `FeatureService` as well and put the try-catch around the corresponding checks.

**Comment by heuermh** [comment]
`IllegalArgumentException`s map nicely to `HTTP 400 Bad Request`, so I was thinking try catch for IAEs around `FeatureService` calls, rethrowing as `UserInputException`s, then using Guava `checkArgument` for both null checks and validity checks in implementations of FeatureService (since `checkNotNull` throws `NullPointerException`).

**Comment by fscheel** [comment]
If you can live with making `null` checks a little more obscure at the price of a nicer catch on the outside, this looks like a very nice way to go. :+1:

**Comment by heuermh** [comment]
On a closer look, the only methods that need not-null argument checking in `FeatureResource` are `createFeature` and `getFeatureByQuery`.  The methods that accept `@PathParam` don't need this, because if a path parameter is missing, the URL pattern will not match.

See #46

**Pull request merged**
